Update theme
pajarorrojo/es-theme-PlayStation-X pull request #9
Opened 2023-04-01 16:10 UTC by TheDayG0ne

- Add ProjectArcade support, logo and nickname
- Update Russian localisation
- Change custom username to Playstation-X

2023-04-02 18:04 UTC, pajarorrojo approved these changes

2023-04-02 18:04 UTC, pajarorrojo approved these changes

2023-04-02 18:07 UTC, pajarorrojo requested changes
please, dont change the green color and the default custom username with playstation-x, this nickname is already in the list

2023-04-03 06:14 UTC, TheDayG0ne commented
Done.

2023-04-03 07:38 UTC, merged